import io
import base64
import requests
from urllib.parse import urlparse
from datetime import datetime

TRANSLATIONS = {
    "en": {
        "title": "Technical SEO Audit Report",
        "overview": "Executive Overview",
        "scores": "Performance Scores",
        "mobile": "Mobile",
        "desktop": "Desktop",
        "onpage": "On-Page SEO Analysis",
        "speed": "Core Web Vitals & Speed",
        "traffic": "Traffic Analytics",
        "ai": "AI Strategic Recommendations",
        "keywords": "Top Organic Keywords",
        "recommendations": "Recommendations",
        "generated_by": "Generated by",
        "prepared_for": "Prepared for",
        "date": "Date",
        "overall_score": "Overall Score",
        "monthly_visits": "Monthly Visits",
        "global_rank": "Global Rank",
        "bounce_rate": "Bounce Rate",
        "avg_duration": "Avg. Duration",
        "pages_per_visit": "Pages/Visit",
        "search": "Organic Search",
        "direct": "Direct",
        "social": "Social",
        "referral": "Referral",
        "score": "Score",
        "issue_found": "Issue Found",
        "passed": "Passed",
        "warning": "Warning",
    },
    "es": {
        "title": "Informe de Auditoría SEO Técnico",
        "overview": "Resumen Ejecutivo",
        "scores": "Puntuaciones de Rendimiento",
        "mobile": "Móvil",
        "desktop": "Escritorio",
        "onpage": "Análisis SEO On-Page",
        "speed": "Core Web Vitals y Velocidad",
        "traffic": "Análisis de Tráfico",
        "ai": "Recomendaciones Estratégicas IA",
        "keywords": "Palabras Clave Orgánicas Principales",
        "recommendations": "Recomendaciones",
        "generated_by": "Generado por",
        "prepared_for": "Preparado para",
        "date": "Fecha",
        "overall_score": "Puntuación General",
        "monthly_visits": "Visitas Mensuales",
        "global_rank": "Rango Global",
        "bounce_rate": "Tasa de Rebote",
        "avg_duration": "Duración Promedio",
        "pages_per_visit": "Páginas/Visita",
        "search": "Búsqueda Orgánica",
        "direct": "Directo",
        "social": "Social",
        "referral": "Referencia",
        "score": "Puntuación",
        "issue_found": "Problema Encontrado",
        "passed": "Aprobado",
        "warning": "Advertencia",
    },
    "fr": {
        "title": "Rapport d'Audit SEO Technique",
        "overview": "Aperçu Exécutif",
        "scores": "Scores de Performance",
        "mobile": "Mobile",
        "desktop": "Bureau",
        "onpage": "Analyse SEO On-Page",
        "speed": "Core Web Vitals et Vitesse",
        "traffic": "Analyse du Trafic",
        "ai": "Recommandations Stratégiques IA",
        "keywords": "Mots-clés Organiques Principaux",
        "recommendations": "Recommandations",
        "generated_by": "Généré par",
        "prepared_for": "Préparé pour",
        "date": "Date",
        "overall_score": "Score Global",
        "monthly_visits": "Visites Mensuelles",
        "global_rank": "Rang Mondial",
        "bounce_rate": "Taux de Rebond",
        "avg_duration": "Durée Moyenne",
        "pages_per_visit": "Pages/Visite",
        "search": "Recherche Organique",
        "direct": "Direct",
        "social": "Social",
        "referral": "Référence",
        "score": "Score",
        "issue_found": "Problème Trouvé",
        "passed": "Réussi",
        "warning": "Avertissement",
    },
    "de": {
        "title": "Technischer SEO-Audit-Bericht",
        "overview": "Zusammenfassung",
        "scores": "Leistungsbewertungen",
        "mobile": "Mobil",
        "desktop": "Desktop",
        "onpage": "On-Page SEO-Analyse",
        "speed": "Core Web Vitals & Geschwindigkeit",
        "traffic": "Verkehrsanalyse",
        "ai": "KI-Strategische Empfehlungen",
        "keywords": "Top Organische Schlüsselwörter",
        "recommendations": "Empfehlungen",
        "generated_by": "Erstellt von",
        "prepared_for": "Erstellt für",
        "date": "Datum",
        "overall_score": "Gesamtpunktzahl",
        "monthly_visits": "Monatliche Besuche",
        "global_rank": "Globaler Rang",
        "bounce_rate": "Absprungrate",
        "avg_duration": "Durchschn. Dauer",
        "pages_per_visit": "Seiten/Besuch",
        "search": "Organische Suche",
        "direct": "Direkt",
        "social": "Sozial",
        "referral": "Referral",
        "score": "Punktzahl",
        "issue_found": "Problem Gefunden",
        "passed": "Bestanden",
        "warning": "Warnung",
    },
    "ar": {
        "title": "تقرير تدقيق تحسين محركات البحث التقني",
        "overview": "نظرة عامة تنفيذية",
        "scores": "درجات الأداء",
        "mobile": "الجوال",
        "desktop": "سطح المكتب",
        "onpage": "تحليل SEO على الصفحة",
        "speed": "Core Web Vitals والسرعة",
        "traffic": "تحليل حركة المرور",
        "ai": "توصيات استراتيجية الذكاء الاصطناعي",
        "keywords": "كلمات مفتاحية عضوية رئيسية",
        "recommendations": "التوصيات",
        "generated_by": "تم الإنشاء بواسطة",
        "prepared_for": "تم الإعداد لـ",
        "date": "التاريخ",
        "overall_score": "النتيجة الإجمالية",
        "monthly_visits": "الزيارات الشهرية",
        "global_rank": "الترتيب العالمي",
        "bounce_rate": "معدل الارتداد",
        "avg_duration": "متوسط المدة",
        "pages_per_visit": "الصفحات/الزيارة",
        "search": "البحث العضوي",
        "direct": "المباشر",
        "social": "الاجتماعي",
        "referral": "الإحالة",
        "score": "النتيجة",
        "issue_found": "تم العثور على مشكلة",
        "passed": "نجح",
        "warning": "تحذير",
    },
    "zh": {
        "title": "技术SEO审计报告",
        "overview": "执行概述",
        "scores": "绩效评分",
        "mobile": "移动端",
        "desktop": "桌面端",
        "onpage": "页面SEO分析",
        "speed": "核心网页指标与速度",
        "traffic": "流量分析",
        "ai": "AI战略建议",
        "keywords": "热门有机关键词",
        "recommendations": "建议",
        "generated_by": "由...生成",
        "prepared_for": "为...准备",
        "date": "日期",
        "overall_score": "总分",
        "monthly_visits": "月访问量",
        "global_rank": "全球排名",
        "bounce_rate": "跳出率",
        "avg_duration": "平均时长",
        "pages_per_visit": "页面/访问",
        "search": "自然搜索",
        "direct": "直接访问",
        "social": "社交媒体",
        "referral": "引荐",
        "score": "评分",
        "issue_found": "发现问题",
        "passed": "通过",
        "warning": "警告",
    },
}

def get_translations(lang="en"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"])

def get_score_color(score):
    if score >= 90:
        return "#10b981"
    elif score >= 50:
        return "#f59e0b"
    else:
        return "#ef4444"

def get_score_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Needs Work"
    else:
        return "Poor"

def generate_html_report_single(url, onpage_data=None, speed_data=None, traffic_data=None, ai_suggestions=None,
                                 agency_name="NexGenWebLab", client_name="Client", author_name="SEO Team",
                                 logo_url="", custom_css="", primary_color="#6D28D9", secondary_color="#DB2777",
                                 language="en", white_label=False):
    if onpage_data is None:
        onpage_data = {}
    if speed_data is None:
        speed_data = {}
    if traffic_data is None:
        traffic_data = {}
    if ai_suggestions is None:
        ai_suggestions = []
    
    return generate_advanced_html_report(
        url=url,
        onpage_data=onpage_data,
        speed_data=speed_data,
        traffic_data=traffic_data,
        ai_suggestions=ai_suggestions,
        agency_name=agency_name,
        client_name=client_name,
        author_name=author_name,
        logo_base64=None,
        custom_css=custom_css,
        primary_color=primary_color,
        secondary_color=secondary_color,
        language=language,
        white_label=white_label,
    )

def generate_advanced_html_report(url, onpage_data, speed_data, traffic_data, ai_suggestions,
                                   agency_name="NexGenWebLab", client_name="Client",
                                   author_name="SEO Team", logo_base64=None, custom_css="",
                                   primary_color="#6D28D9", secondary_color="#DB2777",
                                   language="en", white_label=False):
    
    t = get_translations(language)
    site_title = url
    
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        resp = requests.get(url, headers=headers, timeout=10)
        if resp.status_code == 200:
            import re
            title_match = re.search(r'<title[^>]*>([^<]+)</title>', resp.text, re.I)
            if title_match:
                site_title = title_match.group(1).strip()
    except:
        pass
    
    mobile_score = 50
    desktop_score = 50
    if speed_data:
        mobile_score = speed_data.get('mobile', {}).get('performance', 50) or 50
        desktop_score = speed_data.get('desktop', {}).get('performance', 50) or 50
    avg_score = (mobile_score + desktop_score) // 2
    
    onpage_checks = [
        ('Title Tag', 'Missing' if not onpage_data.get('title') else 'Found', bool(onpage_data.get('title')), onpage_data.get('title', 'Missing')[:50]),
        ('Meta Description', 'Missing' if not onpage_data.get('description') else 'Found', bool(onpage_data.get('description')), onpage_data.get('description', 'Missing')[:80]),
        ('H1 Headings', f"{len(onpage_data.get('h1', []))} found", len(onpage_data.get('h1', [])) > 0, ', '.join(onpage_data.get('h1', [])[:2])[:60] or 'None'),
        ('Word Count', f"{onpage_data.get('word_count', 0)} words", onpage_data.get('word_count', 0) >= 300, str(onpage_data.get('word_count', 0))),
        ('HTTPS/SSL', onpage_data.get('is_https', 'No'), onpage_data.get('is_https', '') == 'Yes', 'Secure' if onpage_data.get('is_https', '') == 'Yes' else 'Not Secure'),
        ('Schema Markup', 'Present' if onpage_data.get('schema') else 'Missing', bool(onpage_data.get('schema')), onpage_data.get('schema', 'Not detected')),
        ('Canonical URL', 'Present' if onpage_data.get('canonical') else 'Missing', bool(onpage_data.get('canonical')), onpage_data.get('canonical', 'Missing')[:60]),
        ('Missing ALT Images', f"{onpage_data.get('missing_alt', 0)} missing", onpage_data.get('missing_alt', 0) == 0, f"{onpage_data.get('missing_alt', 0)} images"),
        ('HTML Size', f"{onpage_data.get('html_size_kb', 0):.1f} KB", onpage_data.get('html_size_kb', 0) < 150, 'Optimal' if onpage_data.get('html_size_kb', 0) < 150 else 'Large'),
        ('Load Time', f"{onpage_data.get('response_time', 0):.2f}s", onpage_data.get('response_time', 0) < 1, 'Fast' if onpage_data.get('response_time', 0) < 1 else 'Slow'),
    ]
    
    passed_count = sum(1 for _, _, passed, _ in onpage_checks if passed)
    issues_count = sum(1 for _, _, passed, _ in onpage_checks if not passed)
    
    html = f'''<!DOCTYPE html>
<html lang="{language}" dir="{"rtl" if language == "ar" else "ltr"}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{t.get('title', 'SEO Audit Report')} - {client_name}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; background: #f1f5f9; color: #1e293b; line-height: 1.6; }}
        
        :root {{
            --primary: {primary_color};
            --secondary: {secondary_color};
            --success: #10b981;
            --warning: #f59e0b;
            --danger: #ef4444;
        }}
        
        .report-wrapper {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
        
        .cover-page {{
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%);
            color: white; min-height: 100vh; display: flex; flex-direction: column;
            justify-content: center; align-items: center; text-align: center; padding: 60px;
            position: relative; overflow: hidden;
        }}
        .cover-page::before {{
            content: ''; position: absolute; top: -200px; right: -200px; width: 600px; height: 600px;
            background: linear-gradient(135deg, var(--primary), transparent); border-radius: 50%; opacity: 0.3;
        }}
        .cover-page::after {{
            content: ''; position: absolute; bottom: -150px; left: -150px; width: 400px; height: 400px;
            background: linear-gradient(135deg, var(--secondary), transparent); border-radius: 50%; opacity: 0.2;
        }}
        .cover-content {{ position: relative; z-index: 1; }}
        .cover-badge {{
            display: inline-block; background: rgba(255,255,255,0.1); padding: 8px 20px;
            border-radius: 50px; font-size: 12px; font-weight: 600; letter-spacing: 2px;
            text-transform: uppercase; margin-bottom: 30px; border: 1px solid rgba(255,255,255,0.2);
        }}
        .cover-title {{ font-size: 52px; font-weight: 800; margin-bottom: 20px; line-height: 1.1; }}
        .cover-subtitle {{ font-size: 20px; opacity: 0.8; margin-bottom: 50px; font-weight: 400; }}
        .cover-meta {{ display: flex; gap: 40px; justify-content: center; flex-wrap: wrap; }}
        .cover-meta-item {{ text-align: left; }}
        .cover-meta-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 2px; opacity: 0.6; margin-bottom: 5px; }}
        .cover-meta-value {{ font-size: 16px; font-weight: 600; }}
        
        .section {{ background: white; border-radius: 20px; padding: 40px; margin: 30px 0; box-shadow: 0 4px 20px rgba(0,0,0,0.05); }}
        .section-header {{ display: flex; align-items: center; gap: 15px; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #f1f5f9; }}
        .section-icon {{ width: 48px; height: 48px; background: linear-gradient(135deg, var(--primary), var(--secondary)); border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 20px; color: white; }}
        .section-title {{ font-size: 24px; font-weight: 700; color: #0f172a; }}
        .section-subtitle {{ font-size: 14px; color: #64748b; margin-top: 4px; }}
        
        .scores-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 25px; }}
        .score-card {{ background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-radius: 16px; padding: 30px; text-align: center; border: 1px solid #e2e8f0; }}
        .score-card-title {{ font-size: 14px; text-transform: uppercase; letter-spacing: 2px; color: #64748b; margin-bottom: 15px; }}
        .score-number {{ font-size: 64px; font-weight: 800; color: var(--primary); line-height: 1; }}
        .score-label {{ font-size: 12px; color: #64748b; margin-top: 10px; text-transform: uppercase; letter-spacing: 1px; }}
        
        .metrics-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }}
        .metric-card {{ background: linear-gradient(135deg, #fafafa, #f5f5f5); border-radius: 12px; padding: 25px; text-align: center; }}
        .metric-value {{ font-size: 26px; font-weight: 800; color: #0f172a; margin-bottom: 5px; }}
        .metric-label {{ font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; }}
        
        .checklist-grid {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; }}
        .check-item {{ display: flex; align-items: flex-start; gap: 15px; padding: 18px; border-radius: 12px; background: #fafafa; }}
        .check-icon {{ width: 28px; height: 28px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 14px; flex-shrink: 0; }}
        .check-icon.pass {{ background: #dcfce7; color: var(--success); }}
        .check-icon.fail {{ background: #fee2e2; color: var(--danger); }}
        .check-content {{ flex: 1; }}
        .check-label {{ font-size: 14px; font-weight: 600; color: #1e293b; margin-bottom: 4px; }}
        .check-value {{ font-size: 12px; color: #64748b; }}
        
        .ai-grid {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; }}
        .ai-card {{ background: linear-gradient(135deg, #f5f3ff, #fdf2f8); border-radius: 12px; padding: 25px; border-left: 4px solid var(--primary); }}
        .ai-card-title {{ font-size: 15px; font-weight: 700; color: #1e293b; margin-bottom: 10px; }}
        .ai-card-text {{ font-size: 13px; color: #64748b; line-height: 1.7; }}
        
        .keywords-table {{ width: 100%; border-collapse: collapse; }}
        .keywords-table th {{ background: #f8fafc; padding: 14px 20px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; border-bottom: 2px solid #e2e8f0; }}
        .keywords-table td {{ padding: 14px 20px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }}
        .keywords-table tr:hover {{ background: #f8fafc; }}
        .position-badge {{ background: var(--primary); color: white; padding: 4px 12px; border-radius: 50px; font-size: 12px; font-weight: 600; }}
        
        .summary-bar {{ display: flex; justify-content: center; gap: 30px; margin-top: 30px; padding: 20px; background: #f8fafc; border-radius: 12px; }}
        .summary-item {{ text-align: center; }}
        .summary-value {{ font-size: 32px; font-weight: 800; color: var(--primary); }}
        .summary-label {{ font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #64748b; margin-top: 5px; }}
        
        .report-footer {{ text-align: center; padding: 40px; color: #64748b; font-size: 12px; border-top: 2px solid #e2e8f0; margin-top: 30px; }}
        .footer-brand {{ color: var(--primary); font-weight: 600; }}
        
        @media print {{ body {{ background: white; }} .cover-page {{ break-after: page; }} }}
    </style>
</head>
<body>
    <div class="report-wrapper">
        <div class="cover-page">
            <div class="cover-content">
                <div class="cover-badge">Technical SEO Audit</div>
                <h1 class="cover-title">{t.get('title', 'Technical SEO Audit Report')}</h1>
                <p class="cover-subtitle">Comprehensive SEO analysis and strategic recommendations</p>
                <div class="cover-meta">
                    <div class="cover-meta-item">
                        <div class="cover-meta-label">{t.get('prepared_for', 'Prepared For')}</div>
                        <div class="cover-meta-value">{client_name}</div>
                    </div>
                    <div class="cover-meta-item">
                        <div class="cover-meta-label">{t.get('date', 'Date')}</div>
                        <div class="cover-meta-value">{datetime.now().strftime('%B %d, %Y')}</div>
                    </div>
                    <div class="cover-meta-item">
                        <div class="cover-meta-label">Target URL</div>
                        <div class="cover-meta-value" style="word-break: break-all;">{url}</div>
                    </div>
                    <div class="cover-meta-item">
                        <div class="cover-meta-label">{t.get('generated_by', 'Generated By')}</div>
                        <div class="cover-meta-value">{agency_name}</div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <div class="section-header">
                <div class="section-icon">📊</div>
                <div>
                    <h2 class="section-title">{t.get('scores', 'Performance Scores')}</h2>
                    <p class="section-subtitle">Performance metrics based on Google Lighthouse analysis</p>
                </div>
            </div>
            <div class="scores-grid">
                <div class="score-card">
                    <div class="score-card-title">{t.get('overall_score', 'Overall Score')}</div>
                    <div class="score-number" style="color: {get_score_color(avg_score)}">{avg_score}</div>
                    <div class="score-label">{get_score_label(avg_score)}</div>
                </div>
                <div class="score-card">
                    <div class="score-card-title">{t.get('mobile', 'Mobile')}</div>
                    <div class="score-number" style="color: {get_score_color(mobile_score)}">{mobile_score}</div>
                    <div class="score-label">{get_score_label(mobile_score)}</div>
                </div>
                <div class="score-card">
                    <div class="score-card-title">{t.get('desktop', 'Desktop')}</div>
                    <div class="score-number" style="color: {get_score_color(desktop_score)}">{desktop_score}</div>
                    <div class="score-label">{get_score_label(desktop_score)}</div>
                </div>
            </div>
            <div class="summary-bar">
                <div class="summary-item">
                    <div class="summary-value">{passed_count}</div>
                    <div class="summary-label">{t.get('passed', 'Passed')}</div>
                </div>
                <div class="summary-item">
                    <div class="summary-value">{issues_count}</div>
                    <div class="summary-label">{t.get('issue_found', 'Issues Found')}</div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <div class="section-header">
                <div class="section-icon">📈</div>
                <div>
                    <h2 class="section-title">Key Performance Metrics</h2>
                    <p class="section-subtitle">Critical indicators for SEO success</p>
                </div>
            </div>
            <div class="metrics-grid">
                <div class="metric-card">
                    <div class="metric-value">{traffic_data.get('global_rank', 'N/A') if traffic_data else 'N/A'}</div>
                    <div class="metric-label">{t.get('global_rank', 'Global Rank')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{traffic_data.get('monthly_visits', 'N/A') if traffic_data else 'N/A'}</div>
                    <div class="metric-label">{t.get('monthly_visits', 'Monthly Visits')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{traffic_data.get('bounce_rate', 'N/A') if traffic_data else 'N/A'}</div>
                    <div class="metric-label">{t.get('bounce_rate', 'Bounce Rate')}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-value">{onpage_data.get('word_count', 0)}</div>
                    <div class="metric-label">Words</div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <div class="section-header">
                <div class="section-icon">✅</div>
                <div>
                    <h2 class="section-title">{t.get('onpage', 'On-Page SEO Analysis')}</h2>
                    <p class="section-subtitle">Technical SEO factors audit</p>
                </div>
            </div>
            <div class="checklist-grid">'''

    for label, value, passed, detail in onpage_checks:
        icon_class = 'pass' if passed else 'fail'
        icon_char = '✓' if passed else '✗'
        html += f'''
                <div class="check-item">
                    <div class="check-icon {icon_class}">{icon_char}</div>
                    <div class="check-content">
                        <div class="check-label">{label}</div>
                        <div class="check-value">{detail}</div>
                    </div>
                </div>'''

    html += '''
            </div>
        </div>'''

    if ai_suggestions and len(ai_suggestions) > 0:
        html += f'''
        <div class="section">
            <div class="section-header">
                <div class="section-icon">🤖</div>
                <div>
                    <h2 class="section-title">{t.get('ai', 'AI Strategic Recommendations')}</h2>
                    <p class="section-subtitle">Strategic recommendations powered by AI</p>
                </div>
            </div>
            <div class="ai-grid">'''
        for item in ai_suggestions[:6]:
            html += f'''
                <div class="ai-card">
                    <div class="ai-card-title">{item.get('title', 'Recommendation')}</div>
                    <div class="ai-card-text">{item.get('text', '')}</div>
                </div>'''
        html += '''
            </div>
        </div>'''

    if not white_label:
        html += f'''
        <div class="report-footer">
            <p>Generated by <span class="footer-brand">{agency_name}</span> | Powered by NexGenWebLab</p>
            <p style="margin-top: 10px;">{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>'''

    html += '''
    </div>
</body>
</html>'''

    return html.encode()

def generate_html_report_bulk(reports_data, agency_name="NexGenWebLab", primary_color="#6D28D9", secondary_color="#DB2777"):
    combined_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bulk SEO Report - {agency_name}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        body {{ font-family: 'Inter', sans-serif; background: #f1f5f9; }}
        .bulk-header {{ background: linear-gradient(135deg, #0f172a, #1e293b); color: white; padding: 60px; text-align: center; }}
        .bulk-header h1 {{ font-size: 42px; margin-bottom: 15px; }}
        .bulk-header p {{ opacity: 0.8; font-size: 18px; }}
        .bulk-summary {{ max-width: 1200px; margin: -40px auto 40px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; }}
        .summary-card {{ background: white; padding: 30px; border-radius: 16px; text-align: center; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }}
        .summary-card h3 {{ font-size: 42px; font-weight: 800; color: {primary_color}; }}
        .summary-card p {{ color: #64748b; margin-top: 8px; }}
        .report-wrapper {{ max-width: 1200px; margin: 0 auto; padding: 20px; }}
    </style>
</head>
<body>
    <div class="bulk-header">
        <h1>Bulk SEO Audit Report</h1>
        <p>{agency_name} | {datetime.now().strftime('%B %d, %Y')}</p>
    </div>
    <div class="bulk-summary">
        <div class="summary-card"><h3>{len(reports_data)}</h3><p>Total Audits</p></div>
        <div class="summary-card"><h3>{sum(1 for r in reports_data if r.get("speed_data", {}).get("mobile", {}).get("performance", 0) >= 80)}</h3><p>Passing Core Web Vitals</p></div>
        <div class="summary-card"><h3>{sum(r.get("onpage_data", {}).get("missing_alt", 0) for r in reports_data)}</h3><p>Total Missing ALTs</p></div>
        <div class="summary-card"><h3>{sum(1 for r in reports_data if r.get("onpage_data", {}).get("is_https") == "Yes")}</h3><p>HTTPS Secure</p></div>
    </div>'''

    for i, rd in enumerate(reports_data, 1):
        report_html = generate_advanced_html_report(
            url=rd.get('url', ''),
            onpage_data=rd.get('onpage_data', {}),
            speed_data=rd.get('speed_data', {}),
            traffic_data=rd.get('traffic_data', {}),
            ai_suggestions=rd.get('ai_suggestions', []),
            agency_name=agency_name,
            client_name=rd.get('client_name', 'Client'),
            author_name=rd.get('author_name', 'SEO Team'),
            primary_color=primary_color,
            secondary_color=secondary_color,
        ).decode('utf-8')
        
        html_body = report_html.replace('<html lang="en">', '<div class="report-wrapper" style="margin: 40px auto; background: white; border-radius: 20px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08);">').replace('</html>', '</div></html>')
        html_body = html_body.replace('<head>', '<div style="background: linear-gradient(135deg, #0f172a, #1e293b); color: white; padding: 20px 30px; font-size: 18px; font-weight: 600;">' + f'Report {i}: {rd.get("url", "N/A")}' + '</div><div class="report-content">').replace('</head>', '</div><div class="report-body">')
        html_body = html_body.replace('<body>', '').replace('</body>', '')
        
        combined_html += html_body

    combined_html += '''
</body>
</html>'''

    return combined_html.encode()